name: font_awesome_flutter_named
description: A build of the fantastic font_awesome_flutter package with all the fonts named.
homepage: https://github.com/peiffer-innovations/font_awesome_flutter_named
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.0
  recase: ^4.0.0
  flutter_test:
    sdk: flutter
  version: ^2.0.0
